import type { ProjectState } from "../domain/project-state";
import { renderProjectFrontmatter } from "./frontmatter";
import { MANAGED_NOTICE } from "./shared";

export const OPERATING_CONTRACT_VERSION = 2 as const;

export function renderOperating(state: ProjectState): string {
  const frontmatter = renderProjectFrontmatter(state, "OPERATING", "operating-contract")
    .replace("\n---\n", `\noperating_contract_version: ${OPERATING_CONTRACT_VERSION}\n---\n`);

  return `${frontmatter}${MANAGED_NOTICE}\n# Operating Contract — ${state.name}\n\nThis generated contract defines the current Project OS working routes for humans and chats. Refresh HANDOFF.md and STATE.md before significant project work, then follow this contract.\n\n## Canonical business state\n\n- Accepted decisions, constraints, tasks, plan/lifecycle changes and accepted research are durable only through typed Project OS transactions.\n- A durable mutation is not considered persisted until its receipt has \`status: committed\`.\n- Generated projections such as STATE.md, HANDOFF.md, ROADMAP.md, TASKS/, DECISIONS/, CONSTRAINTS/ and RESEARCH/ are views of canonical state and must not be directly edited to create canonical truth.\n- MutationGate and Project Guard remain authoritative for governed writes and concurrency.\n\n## Project-session isolation and cross-project routing\n\n- A PROJECT_SESSION must not change its primary project unless the user explicitly asks to switch.\n- Mentioning another project does not authorize rebinding.\n- Ambiguous acknowledgements such as \`go ahead\`, \`ok\`, \`do it\`, or \`continue\` never authorize rebinding.\n- When the user asks to deposit, send, route, or pass information to another project, route the information to the target project's \`INPUTS/\` without changing the current session binding.\n- Do not load the target project's HANDOFF.md or STATE.md merely to deliver the referral. Resolve only the target identity/path needed for delivery.\n- A routed input is evidence/request material, not automatically accepted canonical truth in the target project.\n- A referral should preserve enough provenance to understand its source, target, type, title/body, timestamp, and source evidence when relevant. It does not automatically create a task, decision, research record, or deliverable in the target project.\n\n## Sources and references\n\n- New files supplied for analysis, R&D or evidence enter through \`INPUTS/\`.\n- Intake reconciliation snapshots evidence and routes it to \`REFERENCES/UNCLASSIFIED/\` before optional explicit classification under \`REFERENCES/\`.\n- Existing reference content keeps its governed identity; bootstrap does not bulk-move historical files.\n\n## Collaborative documents\n\n- Drafts and active collaborative work live in \`WORKING/\`.\n- Before editing a managed document, refresh its logical head/current version.\n- Explicit review candidates live in \`REVIEW/\`.\n- Approved or published outputs live in \`DELIVERABLES/\` only through governed publication; direct final-zone edits are not implicit publication.\n\n## Routing summary\n\n- Cross-project referral → target INPUTS/ while current PROJECT_SESSION remains bound\n- Sources → INPUTS/ → REFERENCES/UNCLASSIFIED/ → REFERENCES/\n- Drafts → WORKING/ → REVIEW/\n- Published → DELIVERABLES/\n- Business facts → typed transactions → committed receipt → regenerated projections\n`;
}
