export const MANAGED_NOTICE = "<!-- MACHINE-MANAGED: regenerated by Project Guard. Do not edit generated sections directly. -->";

export function sortedValues<T extends Record<string, unknown>>(record: Record<string, T>, key: keyof T): T[] {
  return Object.values(record).sort((a, b) => String(a[key]).localeCompare(String(b[key])));
}

export function lineOrNone(items: string[]): string {
  return items.length ? items.join("\n") : "- None";
}
