import type { SchemaWriterStage } from "./schema/writer-stage";

export type Env = Omit<
  Cloudflare.Env,
  | "PROJECT_OS_LAYOUT_MODE"
  | "PROJECT_OS_CONTINUITY_MODE"
  | "PROJECT_OS_MUTATION_GATE_MODE"
  | "PROJECT_OS_SCHEMA_WRITER_STAGE"
  | "PROJECT_OS_SCHEMA_CANARY_PROJECT_ID"
  | "PROJECT_OS_SCHEMA_CORE_V2_FLOOR_PROJECT_IDS"
  | "PROJECT_OS_SEARCH_READ_MODE"
  | "PROJECT_OS_SEARCH_SYNC_MODE"
  | "PROJECT_OS_BINARY_ARTIFACT_INGRESS_MODE"
  | "PROJECT_OS_BINARY_ARTIFACT_MAX_BYTES"
  | "PROJECT_OS_REVIEW_CANDIDATE_INGRESS_MODE"
  | "PROJECT_OS_REVIEW_CANDIDATE_CAPABILITY"
  | "PROJECT_OS_CONVERGENCE_PROJECT_MODES"
  | "PROJECT_OS_ADMISSION_PROJECT_MODES"
  | "MUTATION_CONTEXT_SIGNING_KEY"
  | "RULE_ADMISSION_SIGNING_KEY"
  | "PROJECT_OS_MONITORING_WEBHOOK_URL"
  | "PROJECT_OS_MONITORING_WEBHOOK_TOKEN"
> & {
  DROPBOX_APP_KEY: string;
  DROPBOX_APP_SECRET: string;
  DROPBOX_REFRESH_TOKEN: string;
  INGRESS_TOKEN: string;
  RULE_GOVERNANCE_TOKEN?: string;
  CONTROL_TOWER_OPERATOR_TOKEN?: string;
  INPUT_RECOVERY_OPERATOR_TOKEN?: string;
  MUTATION_GATE_OPERATOR_TOKEN?: string;
  PROJECT_OS_LAYOUT_MODE?: "legacy" | "shadow" | "v2";
  PROJECT_OS_CONTINUITY_MODE?: "stable" | "automatic" | "rollback";
  PROJECT_OS_MUTATION_GATE_MODE?: "observe" | "enforce";
  PROJECT_OS_SCHEMA_WRITER_STAGE?: SchemaWriterStage;
  PROJECT_OS_SCHEMA_CANARY_PROJECT_ID?: string;
  PROJECT_OS_SCHEMA_CORE_V2_FLOOR_PROJECT_IDS?: string;
  PROJECT_OS_PROJECTION_CONCURRENCY?: string;
  PROJECT_OS_SEARCH_READ_MODE?: "on" | "off";
  PROJECT_OS_SEARCH_SYNC_MODE?: "on" | "off";
  PROJECT_OS_BINARY_ARTIFACT_INGRESS_MODE?: "on" | "off";
  PROJECT_OS_BINARY_ARTIFACT_MAX_BYTES?: string;
  PROJECT_OS_REVIEW_CANDIDATE_INGRESS_MODE?: "off" | "scoped";
  PROJECT_OS_REVIEW_CANDIDATE_CAPABILITY?: string;
  PROJECT_OS_CONVERGENCE_PROJECT_MODES?: string;
  PROJECT_OS_ADMISSION_PROJECT_MODES?: string;
  MUTATION_CONTEXT_SIGNING_KEY?: string;
  /** Authority held only by RegistryGuard for short-lived rule-admission permits. */
  RULE_ADMISSION_SIGNING_KEY?: string;
  PROJECT_OS_MONITORING_WEBHOOK_URL?: string;
  PROJECT_OS_MONITORING_WEBHOOK_TOKEN?: string;
};
